name: agartu
description: AgartU Social Network
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # state management
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5

  # firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # networking
  dio: ^5.4.1

  # local storage
  shared_preferences: ^2.2.3

  # localization
  easy_localization: ^3.0.7

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
